# Generated by Django 5.0.1 on 2025-08-05 14:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_alert'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='stockprice',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='alert',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='symbol',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='alert',
            name='triggered',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='stockprice',
            name='symbol',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='stockprice',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['user', 'symbol', 'triggered'], name='alerts_aler_user_id_8ccfd4_idx'),
        ),
    ]
