# Generated by Django 5.0.1 on 2025-08-05 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_alter_alert_options_alter_stockprice_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='symbol',
            field=models.CharField(choices=[('AAPL', 'AAPL'), ('GOOGL', 'GOOGL'), ('MSFT', 'MSFT'), ('AMZN', 'AMZN'), ('TSLA', 'TSLA'), ('META', 'META'), ('NVDA', 'NVDA'), ('NFLX', 'NFLX'), ('INTC', 'INTC'), ('AMD', 'AMD')], db_index=True, max_length=10),
        ),
    ]
